### ISSUE TITLE
POST news !!!

### ISSUE THREAD

**Issue by WildClaudio** [horgh/twitter-tcl#16]
i`v just loaded your tcl and works great now i have a question is there a way to AUTO write in IRC channels at X/Y interval of minutes/hours the !twit_updates and be able to set for example to post the last ones ? for example i am following @NASA/@SPACE now to be able to see the last post in IRC channel i must call/give the manual command !twit_updates # , i am asking for an auto script  to be able to make the bot to give the latest news/posts from twits that i Follow  i dont know if you understand !! but i hope you do :P) thank you in advance !!!

**Comment by horgh** [comment]
Hi,

I think what you describe is already possible with the script.

If you change this variable to 1 it should behave like this.

variable poll_home_timeline 0

to

variable poll_home_timeline 1

This is at the top of twitter.tcl.

This will automatically retrieve the latest unseen tweets and show them in your channel. It will happen every 10 minutes by default. You can change that by changing "variable update_time".

Hopefully this helps. Let me know if this is not what you mean.
