### ISSUE TITLE
posting different twitter feeds to different chan

### ISSUE THREAD

**Issue by rinzes** [horgh/twitter-tcl#19]
I'm looking for a way to post different twitter feeds to different chan. ie: twiiter_feed1 post to #chan1 and twitter_feed2 posts to #chan2

**Comment by rinzes** [comment]
I mean using a single account but put tweets from different people I follow into different channels

**Comment by horgh** [comment]
I see. Well as I say the script will need a modification to do that, but it should not be difficult. I can probably figure something out for it on the weekend.

One way would be to have a way to map accounts to channel(s), and have the default go to all `+twitter` channels if the account isn't mapped to specific channel(s). How would that sound?

**Comment by rinzes** [comment]
Sounds like a plan. Thank you for doing this

**Comment by horgh** [comment]
I've made an update to provide this feature. Can you try the latest version in the repository?

The change is in commit d7e788f092

To use it you will need to create a new config file. I included a sample called twitter.conf.sample that describes how to set it. If you need a different one for each bot, you can set it in the `config_file` variable.

The config lets you map specific accounts to output to specific channels. You only need to list accounts you want to limit from outputting to all channels, which is still the default.

**Comment by rinzes** [comment]
ok, this what I have.. 
I have 2 channels.. #swingtrader & #forex
twitter.conf is set for /home/ubuntu/eggdrop/scripts/on/twitter.conf in twitter.tcl
twiiter.tcl is in /eggdrop/scripts/on and is called in my eggdrop.conf with the same source 

here is my twiiter.conf file content
[account-to-channel-mapping]

Stocktwits = #swingtrader
FXstreetNews = #forex
SignalFactory = #forex
DailyFXTeam = #forex
ForexLive = #forex
TalkMarkets = #swingtrader
zerohedge = #swingtrader

all screen names are still going to both channels

**Comment by horgh** [comment]
Thanks for trying it. Your config looks right to me.

I made another change just now. This change is to show more information in the partyline when the script loads. There is also a new partyline command to see the status: `.twitter-status`.

You can use that command in the partyline to have it dump out the mappings it has loaded. Does it show any for you? I'm not sure what's going on!

**Comment by rinzes** [comment]
well.. instead of doing a .rehash I restarted the bot and it's now working. Not sure why. Also, .twitter-status in the partyline produces no output

**Comment by rinzes** [comment]
It's working now... thank you very much

**Comment by horgh** [comment]
Awesome! Thanks for letting me know.
