### ISSUE TITLE
Using twitter across several servers 

### ISSUE THREAD

**Issue by rinzes** [horgh/twitter-tcl#20]
How would one use twitter across several servers.

**Comment by horgh** [comment]
I believe eggdrop itself only support connecting to a single server. Unfortunately because of that you would need to run another bot to do this.

**Comment by rinzes** [comment]
I run multi-bots using diff  config files in a single /eggdrop folder

**Comment by horgh** [comment]
I see. You could do this by having a different `twitter.tcl` for each bot, and changing the `state_file` variable in each so you have a unique one per bot. That file tracks which tweets were already seen/output (along with authentication info etc).

You can make `state_file` a path like `/home/user/bot1.state`

**Comment by rinzes** [comment]
ok I managed to setup an additonal twiiter.tcl. I am getting the twits I follow. However, here is a couple things I'm experiencing.

When I did !follow @wsj I got "Twitter failed or already friends with wsj!" I had to add using my http twiitter acct

When I did !following I only got a portion of the users I follow

**Comment by rinzes** [comment]
I tried to set up another twiiter.tcl for a different server and I placed the twitter.tcl file in a different sub folder of scripts and then changed the state_file variable in the twitter.tcl file and changed the .conf file to point to the source of that folder and did a restart of that bot. When I did .chanset #channel +twitter it started posting twitter feed from the different twitter_acct I previously set up.
