### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by vectr0n** [horgh/twitter-tcl#25]
Hello, I have noticed over the last couple of days the bot had stopped announcing tweets. When I logged into the telnet every time the script goes to check for new tweets it shows an error of:
```
[17:55:00] Update retrieval (home) failed: Incorrect number of arguments, must be an even number.
```
I assume something has changed on twitters end, any help would be appreciated.

**Comment by horgh** [comment]
My bot seems to be working okay. Are you using the latest version from git?

The message looks like one from the call to `::http::formatQuery` in `twitlib.tcl`. Maybe you could add a `putlog $query_list` before and after that call to see if we get past there without error, and so we can know what `$query_list` is if it's causing a problem.

**Comment by horgh** [comment]
There are a couple more `formatQuery` calls in `twitoauth.tcl`. Could you use putlog to see if it's one of them?

**Comment by vectr0n** [comment]
The problem seems to be with a FreeBSD os, when I try it on Linux is works fine.

**Comment by horgh** [comment]
I think it's a difference in the version of Tcl. It looks like a recent commit added a requirement that the number of parameters to `::http::formatQuery` be even. `::twitoauth::uri_escape` uses a single argument.

That's probably why it works on your Linux and mine, but not FreeBSD. Your FreeBSD system probably has a newer version of Tcl with that change.

**Comment by vectr0n** [comment]
Both are running 8.6. I have not updated the FreeBSD tcl port in months, so I highly doubt it's related. I also hadn't restarted the bot in weeks when it just randomly stopped working.

**Comment by horgh** [comment]
Did you figure it out?

**Comment by scottbarnes** [comment]
For anyone else (on FreeBSD?) who gets the error "Update retrieval (home) failed: Incorrect number of arguments, must be an even number.", I fixed it by downgrading tcl86. Obviously this is the approach for incompetents, but seeing as how that describes me perfectly, it seemed a fitting solution.

In terms of specifics, this error cropped up, for me, after upgrading to tcl86-8.6.9 on FreeBSD 12.0-RC3. After downgrading back to tcl86-8.6.8 everything worked as expected. Thanks @horgh for the suggestion.

I figured I'd chime in as this thread is the only relevant one I found and it may help someone else.

**Comment by horgh** [comment]
Hmm, thank you for bringing this up again! I'll see if I can come up with a fix that'll work with both versions.

**Comment by horgh** [comment]
I made a change that I think will fix this to work in either version: 2cbd31299a6664e0d0d5b98e673c977481c733a3

If you get a chance, could you please let me know if you still see errors?

**Comment by scottbarnes** [comment]
I upgraded to tcl86-8.6.9_1, updated twitoauth.tcl, restarted the bot, and everything seems to be working perfectly. Thanks, @horgh!

**Comment by horgh** [comment]
Sweet, thank you for trying it!
