### ISSUE TITLE
Oauth FAILED ()

### ISSUE THREAD

**Issue by WildClaudio** [horgh/twitter-tcl#26]
Hello Oauth is not working for me anymore, well in one word i can't get the request_token, even if i`ve recreated the APP permissions, even created a new API, nothing works ...
I get:
Error: OAuth failure: (code: )

**Comment by horgh** [comment]
I'd guess there is some kind of connection error. I made a change in https://github.com/horgh/twitter-tcl/commit/caca55ad90a3282202b831c195636cc5321780f3 that might show more information about what's wrong. Would you be able to try that please and see if it says anything else about what's wrong?

**Comment by WildClaudio** [comment]
hello i just did and now the error is HTTP:

" Error: OAuth HTTP request failure: HTTP :"

  OS: Linux 2.6.32-042stab138.1
  Process ID: 15354 (parent 1)
  Tcl library: /usr/share/tcltk/tcl8.6
  Tcl version: 8.6.2 (header version 8.6.2)
  Tcl is threaded.
  TLS support is enabled.
  TLS library: OpenSSL 1.0.1t 3 May 2016
  IPv6 support is enabled.
  Socket table: 20/100

tcl: /usr/lib/tcl8.6 /usr/include/tcl /usr/include/tcl8.6
% package require http
2.8.8
% package require tls
1.6
% package require base64
2.4.2
% package require sha1
2.0.3
% package require json
1.3.2
% package require htmlparse
1.2.1

I have to mention i am running on the same machine AS TEST another 
eggdrop 1.8.3  that will post youtube links and https: works great.

**Comment by horgh** [comment]
Strange. Did it work on this machine previously?

If you run this script, what does it show?

```tcl
#!/usr/bin/env tclsh

package require http
package require tls

::http::register https 443 [list ::tls::socket -ssl2 0 -ssl3 0 -tls1 1]

set url https://api.twitter.com
set token [::http::geturl $url -timeout 10000]

set status [::http::status $token]
set err    [::http::error $token]
set code   [::http::code $token]
set ncode  [::http::ncode $token]

::http::cleanup $token

puts "status $status"
puts "error $err"
puts "code $code"
puts "ncode $ncode"
```

You can put it in a file and run it like `tclsh ./request.tcl`.

I wonder if another script on the bot is interfering with the `::http::register`. You could try copying that `::http::register` call into the top of the `::twitoauth::query` proc. i.e., copy it to line 106.
