### ISSUE TITLE
Error: Incorrect number of arguments

### ISSUE THREAD

**Issue by sacredland** [horgh/twitter-tcl#27]
Hi, the tcl was working great. I had to rebuilt the vps, and then, one same eggdrop version that it was, same box, I always get in DCC:
<(s)twitter> [21:10:00] Update retrieval (home) failed: Incorrect number of arguments, must be an even number.

Or on chan:
<user> !tweet boo
<twitter> Tweet failed! (boo) Error: Incorrect number of arguments, must be an even number..
<user> !twit_request_token (consumer key) (consumer secret)
<twitter> Error: Incorrect number of arguments, must be an even number.

**Comment by horgh** [comment]
Could you check if the .tcl files from here are up to date? There was a backwards incompatible change in Tcl 8.6.9 that broke the script but I fixed it in 2cbd31299a6664e0d0d5b98e673c977481c733a3 a while back. It sounds like that issue.

**Comment by sacredland** [comment]
Yes tcl are up to date. Now im getting Error: OAuth HTTP request failure: HTTP 401: {"errors":[{"code":32,"message":"Could not authenticate you."}]}. but same token works on our website (ircdrama.ca) as we got the feeds. I got another bot running this tcl on another network.. no update since 2017 and still up&working a1

**Comment by sacredland** [comment]
twitoauth wasnt updated, thanks.
