### ISSUE TITLE
Direct messages not working

### ISSUE THREAD

**Issue by venatiodecorus** [horgh/twitter-tcl#29]
I have API access set for DMs but whenever I try to do it I get a HTTP 404 error:

```
Message to venatiodecorus failed (OAuth HTTP request failure: HTTP 404: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]})! Are they following you?
```

**Comment by horgh** [comment]
Sorry, I somehow missed this. I don't think this will work as is regardless now that Twitter's API changed and we'd need to switch to their v2 API. We're discussing that in #34.
