### ISSUE TITLE
Tweet format in #channel

### ISSUE THREAD

**Issue by angelperezleon** [horgh/twitter-tcl#30]
Not an issue, but a request please.
How can I set the format output of each tweet posted in the channel to show the tweet handle (@user) to show up in bold as is shows better in-channel rather than a bland unformatted plain text all the way.

Example:

**_@NASA:_**  Earth isn't the only place with rivers, lakes & seas.  Saturn’s moon Titan has them, too — not of water, but liquid methane & ethane! This frigid world even hides a liquid water ocean deep beneath its surface.

Something like above...

**Comment by horgh** [comment]
Hmm, isn't the name already bold?

There's no config for changing the output really. If you want to adjust it, you can edit this function: https://github.com/horgh/twitter-tcl/blob/master/twitter.tcl#L178-L184

**Comment by angelperezleon** [comment]
Thanks @horgh 
Looks like @ line 179 of twitter.tcl, you definitely should see a bold output on the $name but in the #channel in question I had +c which is no formatting not allowed (Strip colour and formatting codes from channel messages.) in the chan. Will see if taking this mlock of the chan works.

**Comment by angelperezleon** [comment]
Closing works after removing +c mlock ofc 👯
