### ISSUE TITLE
Update retrieval (home) failed: Unsupported URL type "https"

### ISSUE THREAD

**Issue by angelperezleon** [horgh/twitter-tcl#32]
I am getting this when I have other tcl scripts i believe that use the http package?

`Update retrieval (home) failed: Unsupported URL type "https"`

Is there a way to avoid this problem while using other script.
If I disable twitter script and enable weather & google sepparte scripts, this problem does not arise.

**Comment by horgh** [comment]
How are you including the script? Maybe if you load this one before the others it would work? Or maybe load it last? It sounds like something is overriding the `http::register` calls that sets up https support.

**Comment by horgh** [comment]
I see. I'm not sure what's going on. Could you try this change and see if it helps? https://github.com/horgh/twitter-tcl/commit/dff84ba146a27b35e9c65794f426128ecb56205e

**Comment by horgh** [comment]
Cool, thanks for testing it! I'll merge that in then.
