### ISSUE TITLE
Update retrieval (home) failed: OAuth HTTP request failure: HTTP 401

### ISSUE THREAD

**Issue by angelperezleon** [horgh/twitter-tcl#34]
Getting this error looping round in telnet console for my eggdrop:
`Update retrieval (home) failed: OAuth HTTP request failure: HTTP 401: {"errors":[{"code":32,"message":"Could not authenticate you."}]}`

Have checked on Twitter deleveloper, under my Project section amd see under my App details that my project is flagged as "SUSPENDED" with following message: 
"Update retrieval (home) failed: OAuth HTTP request failure: HTTP 401: {"errors":[{"code":32,"message":"Could not authenticate you."}]}"

Been using this twitter developer app with very little down time over the past 2.5years, but over the past few days my eggdrop failed to do any tweets from those it follows into the channel. 

Have looked on twitter help center but dont see much in way to point out how to find out what the issue was or why its suspended.

Anyone else encountered this problem recently?

**Comment by angelperezleon** [comment]
I saw this over at Twitter developer Platform
https://developer.twitter.com/en/support/twitter-api/policy
`**What will happen if I violate the Twitter developer terms?**
Twitter takes privacy seriously, and we expect everyone using Twitter Content and the Twitter API to do the same. Any use of the Twitter developer platform, Twitter API, or Twitter Content in a manner that is inconsistent with peoples’ reasonable expectations of privacy may be subject to enforcement action, which can include suspension and termination of API and Twitter Content access.

If we believe you are in violation of this Policy (or any other Twitter policy), we may suspend or permanently revoke your access to the Twitter API and Twitter Content. If this happens to you, do not apply for or register additional API keys. Instead, contact us via the [API Policy Support form](https://help.twitter.com/forms/platform).  

Also see our frequently asked questions on [App suspension](https://developer.twitter.com/en/support/twitter-api/policy.html#faq-app-permissions).`

**Comment by horgh** [comment]
Unfortunately AFAIK Twitter closed the API recently. There's no way to read tweets now without paying I believe. See the API tiers [here](https://developer.twitter.com/en/products/twitter-api). That is probably why it has stopped working.

**Comment by angelperezleon** [comment]
Saw this as well @horgh https://developer.twitter.com/en/support/twitter-api/policy
`**How will I know if my App is suspended?**
The Twitter policy team will send a notification to the App owner's Twitter email address if a policy action has been taken on the App.  This email will come from the email address support@twitter.comand will have a subject similar to "Application Suspension Notice".

Within the developer portal, a suspended App will have a red label to show that the App is suspended. API requests made by a suspended App will result in an error similar to:

{"errors": [{"code": 32,"message": "Could not authenticate you."}]}`

**Comment by horgh** [comment]
Yes, you should have received an email from them last month. I did at least. It says that to continue using it, we have to use one of the new access tiers.

**Comment by horgh** [comment]
From a quick look I believe v2 only changes the URLs for what we use here, so it should work if you switch the URLs. I haven't tested it as I no longer have access. I believe the old API version still works for the time being.

I don't think twitter blue will give you enough access to read tweets with the API, but I could be wrong.

**Comment by angelperezleon** [comment]
Which url and where do I change these?

**Comment by horgh** [comment]
I looked at their API docs and I was mistaken. The API is indeed different for v2, so it would involve more than changing URLs. Anyway, the v1.1 API should still work assuming you have API access.

**Comment by angelperezleon** [comment]
I did try by creating new project after my old project was set to suspended, but bot respond with same usual response code as per subject of this issue, so gettign brain fog how to get around this.
Just sounds like old residual api details are in use and cat supplent in the new details.
When you have time be nice if you can get a workign version up, if its a case of not having a workign bot happy to provide access  to mine or ask me where I can implement changes... looked through all 3 main tcl scripts, and made changes within twitlib.tcl under this section
`	# OAuth authentication information.
	variable oauth_consumer_key {}
	variable oauth_consumer_secret {}
	variable oauth_token {}
	variable oauth_token_secret {}`
but had no joy, so stuck getting a working response.
Also notice that FREE API only allow limited access, and BASIC API v2 access seems to be one worthwhile as main purpose of the bot tweeting out within irc chan was to announce tweets from influential SpaceX people within chan.
That option to port tweets & re-tweets no longer available on FREE access.
BASIC cost of $100.00 USD/month just too much to afford.

**Comment by sypha0x** [comment]
I believe it's a security issue. Many companies are now rejecting -tls1 flag for https, I've found I had to upgrade my TLS handshake to integrate as expected from the server side by updating the following below to handle the POODLE issue correctly. This is the recommended change as I've been able to fix recent issues related to this. I suspect their server must of also detected an issue using this old handshake method. The current tls 1.7 package resolves the problem with -autoservername set to true as shown below. Just a heads up because may servers have rejected the older handshake & I have found it to be the underlying issue using the -tls1. 

package require http 2package require tls 1.7
http::register https 443 [list ::tls::socket -autoservername true]




Sent from Yahoo Mail on Android 
 
  On Wed, May 3, 2023 at 5:04 PM, ***@***.***> wrote:   


Getting this error looping round in telnet console for my eggdrop:
Update retrieval (home) failed: OAuth HTTP request failure: HTTP 401: {"errors":[{"code":32,"message":"Could not authenticate you."}]}

Have checked on Twitter deleveloper, under my Project section amd see under my App details that my project is flagged as "SUSPENDED" with following message:
"Update retrieval (home) failed: OAuth HTTP request failure: HTTP 401: {"errors":[{"code":32,"message":"Could not authenticate you."}]}"

Been using this twitter developer app with very little down time over the past 2.5years, but over the past few days my eggdrop failed to do any tweets from those it follows into the channel.

Have looked on twitter help center but dont see much in way to point out how to find out what the issue was or why its suspended.

Anyone else encountered this problem recently?

**Comment by horgh** [comment]
From what I know, the only way to make it work again is to pay for the basic access at $100/month.

**Comment by gh0stmakeitw0rkx** [comment]
> From what I know, the only way to make it work again is to pay for the basic access at $100/month.

I just subscribed to Basic, still Tweet failed!

Tweet failed! (test) Error: OAuth HTTP request failure: HTTP 403: {"errors":[{"message":"You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: [https://developer.twitter.com/en/portal/product","code":453](https://developer.twitter.com/en/portal/product%22,%22code%22:453)}]}

**Comment by angelperezleon** [comment]
![Twitter API v2 Costs](https://github.com/horgh/twitter-tcl/assets/25584631/f8b32123-64de-4592-b429-5d0f23c76ad1)
As you can see from attached image the Basic packer of Twitter v2 API should cater for those of us wanting to retrieve tweets.  Upto 10k tweet per month for a cost of 100$/m.
I just don't have that amount of money laying around to risk if it true or not and works with this script.
Before Elon Musk and Twitter imposed the API limits, I was able to use the script freely without interruptions without problems.

**Comment by horgh** [comment]
> I just subscribed to Basic, still Tweet failed!

Unfortunately even with Basic, it says that the v1.1 API only works for a subset of features:

> (Only Media Upload, Help, Rate Limit, and Login with Twitter)

I don't know if this is another new change or not. I don't recall it being this way when I last looked but maybe I missed it.

However that means even with Basic you will need to use the v2 API to post tweets or read timelines. This script only supports v1.1 so it isn't going to work today. Sorry about that. It looks like above I thought it would work.

**Comment by angelperezleon** [comment]
Hi @horgh 
So by the sounds of it?  Your wont be implementing API v2 in the future into the script?

**Comment by horgh** [comment]
I wasn't planning on it. I'm not inclined to pay for the access. I'd probably accept a pull request though!

**Comment by angelperezleon** [comment]
> > From what I know, the only way to make it work again is to pay for the basic access at $100/month.
> 
> I just subscribed to Basic, still Tweet failed!
> 
> Tweet failed! (test) Error: OAuth HTTP request failure: HTTP 403: {"errors":[{"message":"You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: [https://developer.twitter.com/en/portal/product","code":453](https://developer.twitter.com/en/portal/product%22,%22code%22:453)}]}

I am sure @horgh horgh will be happy to work with you now that you have basic package setup and utilize your env for testing/tweetking the script to work...

**Comment by horgh** [comment]
I could take a look. Are you on IRC somewhere?

**Comment by gh0stmakeitw0erkx** [comment]
> I could take a look. Are you on IRC somewhere?

I sent you a private message on Libera.Chat.

**Comment by angelperezleon** [comment]
am on libera too, wana DM me the chan you guysa re in?

**Comment by gh0stmakeitw0erkx** [comment]
I just created #twittertcl on Libera.Chat. Lets meet there.

**Comment by moonlightz** [comment]
Just received an email from William that this topic is being discussed.

After the v1.1 api script stopped working, I looked for alternatives like twitter ruby gem, even had to make a wrapper in tcl but few weeks after, it stopped working again. I was again looking for alternatives like tweepy but it's hard to setup and python 3.11's new restrictive environment. It's been now few weeks without having any tweets playing on irc channels .

So I hope, this script to be revived once more.
I am in Libera as KashinKoji.

**Comment by horgh** [comment]
Closing this given #35
